= Covalent

This project contains bits to enable communication between a JVM or CLR Clojure project and an Electron app housing a https://github.com/Lokeh/punk[punk] UI.

== Use with Arcadia Project

1. See and follow the instructions at the end of src/covalent/core.cljc, but be sure to start the Unity project before trying to connect to the Arcadia socket repl.

2. For connecting to the Arcadia socket repl, host might be ::1 or 127.0.0.1, but the port is likely 37220

== Use with CLR Clojure Project

1. See and follow the instructions at the end of src/covalent/core.cljc

2. For starting a CLR Clojure socket repl in a *nix like environment, one way is:

```
Clojure.Main.exe \
  -e "(do (require 'clojure.core.server) \
        (clojure.core.server/start-server \
          {:name \"socket-repl\" \
           :port 8991 \
           :accept 'clojure.main/repl \
           :address \"localhost\"}))" \
  -r
```

That should result in a socket repl listening on port 8991.  The host may be ::1 or 127.0.0.1 depending on your platform.

== Use with JVM Clojure Project

1. See and follow the instructions at the end of src/covalent/core.cljc

2. Relax that the tooling has been polished over the years...

== Acknowledgments

Thanks to (at least) the following folks:

* darwin
* dmiller
* kajism
* Lokeh
* Saikyun
* stuarthalloway
* theophilusx
* thheller

